#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]
prepend_keymap = [
	{ on = "l",          run = "plugin smart-enter",             desc = "Enter child directory or open file" },
	{ on = [ "T", "h" ], run = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane" },
	{ on = [ "T", "m" ], run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
	{ on = "z",          run = "plugin zoxide",                  desc = "Jump to a directory via zoxide" },
	{ on = "Z",          run = "plugin fzf",                     desc = "Jump to a file/directory via fzf" },
]
