#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
sort_translit  = false
linemode       = "none"
show_hidden    = false
show_symlink   = true
scrolloff      = 5

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_delay     = 30
image_filter    = "triangle"
image_quality   = 75
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
edit = [
	{ run = '${EDITOR:-nvim} %s', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'code %s',            desc = "code",         orphan = true, for = "windows" },
	{ run = 'code -w %s',         desc = "code (block)", block = true,  for = "windows" },
]
play = [
	{ run = 'mpv --force-window %s', orphan = true, for = "unix" },
	{ run = 'mpv --force-window %s', orphan = true, for = "windows" },
	{ run = '''mediainfo %s1; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"
